const GET_DETAIL = "GET_DETAIL";
const NEXT_PAGE = "NEXT_PAGE";
const PREV_PAGE = "PREV_PAGE";
const SPECIFIC_PAGE = "SPECIFIC_PAGE";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const GET_ALL_HOTELS = "GET_ALL_HOTELS";
const GET_HOTEL_BY_NAME = "GET_HOTEL_BY_NAME";
const DELETE_HOTEL = "DELETE_HOTEL";
const FILTER_BY_COUNTRY = "FILTER_BY_COUNTRY";
const SORT_BY_PRICE = "SORT_BY_PRICE";
// const POST_HOTEL = "POST_HOTEL"
// const GET_COUNTRIES = "GET_COUNTRIES"
const SET_ITEMS = "SET_ITEMS";
const SET_TOTAL_PAGES = "SET_TOTAL_PAGES";

export {
  NEXT_PAGE,
  PREV_PAGE,
  SPECIFIC_PAGE,
  SET_CURRENT_PAGE,
  GET_ALL_HOTELS,
  GET_HOTEL_BY_NAME,
  GET_DETAIL,
  DELETE_HOTEL,
  FILTER_BY_COUNTRY,
  SORT_BY_PRICE,
  // POST_HOTEL,
  // GET_COUNTRIES,
  SET_ITEMS,
  SET_TOTAL_PAGES
};
