const NEXT_PAGE = "NEXT_PAGE";
const PREV_PAGE = "PREV_PAGE";
const SPECIFIC_PAGE = "SPECIFIC_PAGE";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const GET_ALL_HOTELS = "GET_ALL_HOTELS";
const GET_HOTEL_BY_NAME = "GET_HOTEL_BY_NAME";

export {
  NEXT_PAGE,
  PREV_PAGE,
  SPECIFIC_PAGE,
  SET_CURRENT_PAGE,
  GET_ALL_HOTELS,
  GET_HOTEL_BY_NAME,
};
