const GET_DETAIL = "GET_DETAIL";
const NEXT_PAGE = "NEXT_PAGE";
const PREV_PAGE = "PREV_PAGE";
const SPECIFIC_PAGE = "SPECIFIC_PAGE";
const GET_ALL_HOTELS = "GET_ALL_HOTELS";
const CLEAR_HOTELS_FILTERS = "CLEAR_HOTELS_FILTERS";
const GET_HOTEL_BY_NAME = "GET_HOTEL_BY_NAME";
const DELETE_HOTEL = "DELETE_HOTEL";
const FILTER_BY_COUNTRY = "FILTER_BY_COUNTRY";
const SORT_BY_PRICE = "SORT_BY_PRICE";
// const POST_HOTEL = "POST_HOTEL"
// const GET_COUNTRIES = "GET_COUNTRIES"
const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
const FILTER_HOTELS = "FILTER_HOTELS";
const RESET_CURRENT_PAGE = "RESET_CURRENT_PAGE";
const HANDLE_FILTERS = "HANDLE_FILTERS";
const RESET_FILTERS = "RESET_FILTERS";
const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
const SHOW_MODAL = "SHOW_MODAL";
const USER_LOG = "USER_LOG";
const GET_ALL_FAVORITES = "GET_ALL_FAVORITES";
const POST_FAVORITES = "POST_FAVORITES";
const USER_FAVORITES = "USER_FAVORITES";
const USER_REVIEWS = "USER_REVIEWS";
const HOTEL_FAVORITES = "HOTEL_FAVORITES";
const POST_FAVORITE = "POST_FAVORITE";
const REMOVE_FAVORITE = "REMOVE_FAVORITE";
const ADD_WEBSOCKET = "ADD_WEBSOCKET";
const SET_WEBSOCKET = "SET_WEBSOCKET";
const DETAIL_FILTER_PARAMS = "DETAIL_FILTER_PARAMS";
const SET_SELECTED_OPTION = "SET_SELECTED_OPTION"
const SET_CURRENCY = "SET_CURRENCY"

export {
  NEXT_PAGE,
  PREV_PAGE,
  SPECIFIC_PAGE,
  GET_ALL_HOTELS,
  CLEAR_HOTELS_FILTERS,
  GET_HOTEL_BY_NAME,
  GET_DETAIL,
  DELETE_HOTEL,
  FILTER_BY_COUNTRY,
  SORT_BY_PRICE,
  // POST_HOTEL,
  // GET_COUNTRIES,
  FETCH_ITEMS_SUCCESS,
  FILTER_HOTELS,
  RESET_CURRENT_PAGE,
  HANDLE_FILTERS,
  RESET_FILTERS,
  GET_ALL_COUNTRIES,
  SHOW_MODAL,
  USER_LOG,
  GET_ALL_FAVORITES,
  POST_FAVORITES,
  USER_FAVORITES,
  USER_REVIEWS,
  HOTEL_FAVORITES,
  POST_FAVORITE,
  REMOVE_FAVORITE,
  DETAIL_FILTER_PARAMS,
  SET_SELECTED_OPTION,
  ADD_WEBSOCKET,
  SET_WEBSOCKET,
  SET_CURRENCY
};
